steps:
- name: 'jekyll/minimal'
  args: ['jekyll', 'build', '--destination', '/workspace/_site']
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/aryeelab/www-aryee
  - --destination=gcr.io/aryeelab/www-aryee:$SHORT_SHA
  - --build-arg=VERSION=$SHORT_SHA
  - --cache=true
  - --cache-ttl=720h
timeout: 7200s